pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
		stage('Sonar') {
			steps {
				withSonarQubeEnv('My SonarQube Server') {
					sh 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false'
					sh 'mvn sonar:sonar'
				}
/* 				sh 'mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false'
				sh 'mvn sonar:sonar \
					-Dsonar.host.url=https://c70ab213.ngrok.io \
					-Dsonar.login=e1989d283b8d20cd63f95a1c75a41f36e084f149' */
			}
		}
		stage('Quality Gates') {
			steps {
				timeout(time: 5, unit: 'MINUTES') {
					waitForQualityGate abortPipeline: true
				}
			}
		}
    }
}
